version: '3'

networks:
  idea2app:

services:
  web-site:
    image: freecodecamp-china/web-site
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - 3000:3000
    networks:
      - idea2app
  caddy:
    depends_on:
      - web-site
    image: caddy
    ports:
      - 80:80
      - 443:443
    networks:
      - idea2app
    command: caddy reverse-proxy --from your.domain.com --to web-site:3000
